[package]
name = "label"
version = "0.1.0"
authors = ["Pierre Marchand <pierremarc07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = {version="0.17.1"}
rand = "0.8.3"
apply = { path = "../apply" }
