[package]
name = "mafe"
version = "0.1.0"
authors = ["Pierre Marchand <pierre-m@atelier-cartographique.be>"]
edition = "2018"


[dependencies]
clap = "2.33.3"
piet-common = "0.4.1"
apply = { path = "../apply" }
parser = { path = "../parser" }
